# Generated by Django 2.2.3 on 2019-11-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contactNum', models.IntegerField()),
                ('query', models.CharField(max_length=100)),
                ('query_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
